module.exports = function(sequelize, DataTypes){
    var DryCleaningPrices = sequelize.define("DryCleaningPrices",{
        sameDayService:{
            type: DataTypes.BOOLEAN,
            defaultValue: false
        }, 
        delivery:{
            type: DataTypes.BOOLEAN,
            defaultValue: false
        },
        pickUpFee:{
            type:DataTypes.STRING,
            defaultValue: "Enter Info"
        },
        freePickUp:{
            type: DataTypes.BOOLEAN,
            defaultValue: false
        },
        deliveryOrderMinimum:{
            type:DataTypes.STRING
        },
        dryCleaningPrices:{
            type:DataTypes.STRING
        },
        dryCleaningPrices2:{
            type:DataTypes.STRING
        },
        dryCleaningPrices3:{
            type:DataTypes.STRING
        },
        dryCleaningPrices4:{
            type:DataTypes.STRING
        },
        dryCleaningPrices5:{
            type:DataTypes.STRING
        },
        dryCleaningPrices6:{
            type:DataTypes.STRING
        },
        dryCleaningPrices7:{
            type:DataTypes.STRING
        },
        dryCleaningPrices8:{
            type:DataTypes.STRING
        },
        dryCleaningPrices9:{
            type:DataTypes.STRING
        },
        dryCleaningPrices10:{
            type:DataTypes.STRING
        },
        dryCleaningPrices11:{
            type:DataTypes.STRING
        },
        dryCleaningPrices12:{
            type:DataTypes.STRING
        },
        dryCleaningPrices13:{
            type:DataTypes.STRING
        },
        dryCleaningPrices14:{
            type:DataTypes.STRING
        },
        dryCleaningPrices15:{
            type:DataTypes.STRING
        },
        dryCleaningPrices16:{
            type:DataTypes.STRING
        },
        dryCleaningPrices17:{
            type:DataTypes.STRING
        },
        dryCleaningPrices18:{
            type:DataTypes.STRING
        },
        dryCleaningPrices19:{
            type:DataTypes.STRING
        },
        dryCleaningPrices20:{
            type:DataTypes.STRING
        },
        dryCleaningPrices21:{
            type:DataTypes.STRING
        },
        dryCleaningPrices22:{
            type:DataTypes.STRING
        },
        dryCleaningPrices23:{
            type:DataTypes.STRING
        },
        dryCleaningPrices24:{
            type:DataTypes.STRING
        },
        dryCleaningPrices25:{
            type:DataTypes.STRING
        },
        dryCleaningPrices26:{
            type:DataTypes.STRING
        },
        dryCleaningPrices27:{
            type:DataTypes.STRING
        },
        dryCleaningPrices28:{
            type:DataTypes.STRING
        },
        dryCleaningPrices29:{
            type:DataTypes.STRING
        },
        dryCleaningPrices30:{
            type:DataTypes.STRING
        },
        addInfo:{
            type:DataTypes.TEXT 
        },
        addInfo2:{
            type:DataTypes.TEXT 
        },
        addInfo3:{
            type:DataTypes.TEXT 
        },
        sameDayInfo:{
            type:DataTypes.TEXT 
        },
        deliveryHours:{
            type:DataTypes.STRING 
        },
        pickUpHours:{
            type:DataTypes.STRING 
        },
        createdAt:{
            type:DataTypes.DATE
        }, 
        updatedAt:{
            type:DataTypes.DATE
        } 
    })
    DryCleaningPrices.associate=function(models){
        DryCleaningPrices.belongsTo(models.Establishment,{
            foreignKey: {
                allowNull: false
            } 
        })
    }
    return DryCleaningPrices;
}
